### ISSUE TITLE
not working for following data set

### ISSUE THREAD

**Issue by saurabhsinha** [vlio20/one-day#1]
[
        {"id": 1, "start": 60,  "end": 150},
        {"id": 2, "start": 540, "end": 570},
        {"id": 3, "start": 555, "end": 600},
        {"id": 4, "start": 585, "end": 660},
        {"id": 5, "start": 90,  "end": 600},
        {"id": 6, "start": 180,  "end": 240},
        {"id": 7, "start": 300,  "end": 345},
        {"id": 8, "start": 210,  "end": 240}
    ]

for the this data set the solution is not working. as for id 1 and 7, the width is not appropriate.

**Comment by vlio20** [comment]
the width of each colliding event should be the same, event 1 collides with event 5 - and that is the reason why event 1 gets the width it gets (event 1 width has to be the same width as event 5). 
The same happens for event 7.

Note that there is no requirement to fill the hole line.
[see this screen shot](http://i.imgur.com/W05HAqi.png)

@saurabhsinha, does it makes sense?

**Comment by saurabhsinha** [comment]
yes , But what if I want to adjust width for 1 and 7 to fill whole area till event 5.

**Comment by vlio20** [comment]
but this are not the requirements of this question. 
In order to make it adjust there should be a different algorithm.

**Comment by saurabhsinha** [comment]
with this algorithm Its not possible ?

**Comment by vlio20** [comment]
Nope, it never intended.
